branch-defaults:
  master:
    environment: looking-glass-env
    group_suffix: null
global:
  application_name: cs23-looking-glass
  branch: null
  default_ec2_keyname: null
  default_platform: python-3.11
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
